spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/joa?serverTimezone=UTC # mysql 8.2, mysql workbench 8.0.21 / mac? 8.0.34
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import:
      - optional:env/env.yml

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost #로컬이 아닌 경우 redis로 변경
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

error:
  printStackTrace: true

jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    expiration: 10800000 # 3600000 : 60(분) * 60(초) * 1000 -> 1 시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh
