spring:
  mail:
    host: smtp.gmail.com
    port: 587 # 587, 465, 25
    username: joa13site@gmail.com
    password: nryowoqhrnmbzrxr
    properties:
      mail:
        debug: true
        smtp:
          timeout : 5000
          starttls:
            enable: true
            required : true
          auth: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/joa?serverTimezone=UTC # mysql 8.2, mysql workbench 8.0.21 / mac? 8.0.34
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: joa13.site #로컬이 아닌 경우 redis로 변경
      port: 6379
      password: redis

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: 272e7de515b361eabcabb838422dc2a405c3e5c0d8e4b844d08e767d929d2ba8
  access:
    expiration: 7200
    header: Authorization
  refresh:
    expiration: 86400
    header: Authorization-refresh
