spring:
#  mail:
#    host: smtp.naver.com
#    port: 465
#    username: sulim0314@naver.com
#    password: Nrd
#    properties:
#      mail:
#        debug: true
#        smtp:
#          ssl:
#            enable: true
#            trust: smtp.gmail.com
#            protocols: TLSv1.2
#          auth: true
#          timeout: 5000
#          starttls:
#            enable: true

  mail:
    host: smtp.gmail.com
    port: 587 # 587, 465, 25
    username: joa13site@gmail.com
    password: nryowoqhrnmbzrxr
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            enable: true
            trust: smtp.gmail.com
            protocols: TLSv1.2
          auth: true
          timeout: 5000
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/joa?serverTimezone=UTC # mysql 8.2, mysql workbench 8.0.21 / mac? 8.0.34
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import:
      - optional:env/env.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: joa13.site #로컬이 아닌 경우 redis로 변경
      port: 6379
      password: redis

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

error:
  printStackTrace: true

jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    expiration: 10800000 # 3600000 : 60(분) * 60(초) * 1000 -> 1 시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh
